name: universal_ffi
description: A drop-in replacement for dart:ffi for all platforms including web (using wasm_ffi).
version: 1.2.0
repository: https://github.com/vm75/universal_ffi

environment:
  sdk: ^3.5.1

dependencies:
  ffi: ^2.1.3
  path: ^1.9.0
  wasm_ffi: ^2.1.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0

topics:
 - ffi
 - wasm
 - native
 - web
 - cross-platform

platforms:
  android:
  ios:
  linux:
  macos:
  windows:
  web:
