name: universal_ffi
description: A drop-in replacement for dart:ffi for all platforms including web (using wasm_ffi).
version: 1.4.0
repository: https://github.com/vm75/universal_ffi

environment:
  sdk: ^3.10.8

dependencies:
  ffi: ^2.1.5
  path: ^1.9.1
  wasm_ffi: ^2.2.0

dev_dependencies:
  lints: ^6.1.0
  test: ^1.29.0

topics:
 - ffi
 - wasm
 - native
 - web
 - cross-platform

platforms:
  android:
  ios:
  linux:
  macos:
  windows:
  web:
